baseURL = "https://sketchthedocs.dev/visual-green-tech/"
languageCode = "en-us"
title = "Visual Green Tech"
theme = "newsroom"

# Customizing theme based on exampleSite
author = "Nitya"
copyright = "Copyright © 2021, Nitya Narasimhan; all rights reserved."
canonifyurls = true
defaultContentLanguage = "en"
paginate = 6

# Build target directory defined
publishdir = "../docs" 
